const Images = {
  logo: require('./logo/logo.png'),
  rounded: require('./img_rounded.png'),
  shape: require('./img_shape.png'),
  folderStar: require("./image_folder_star.png"),
  shieldTick: require("./image_shield_tick.png"),
  logo4: require("./logo_4.png"),
  notifications: require("./campana.png"),
  policy: require("./privacy-policy.png"),
  questions: require("./question.png"),
  subscriptions: require("./subscription.png"),
  arrow: require("./right-arrow.png"),
  videoCall:require("./video-call.png"),
  onboarding: {
    onboarding01: require('./onboarding/img_intro_1.png'),
    onboarding02: require('./onboarding/img_intro_2.png'),
    onboarding03: require('./onboarding/img_intro_3.png'),
    onboarding04: require('./onboarding/img_intro_4.png'),
    onboarding05: require('./onboarding/img_intro_5.png'),
    onboarding06: require('./onboarding/img_intro_6.png'),
    onboarding07: require('./onboarding/img_intro_7.png'),
    onboarding08: require('./onboarding/img_intro_8.png'),
    onboarding09: require('./onboarding/img_intro_9.png'),
    onboarding10: require('./onboarding/img_intro_10.png'),
    onboarding11: require('./onboarding/img_intro_11.png'),
    onboarding12: require('./onboarding/img_intro_12.png'),
    onboarding13: require('./onboarding/img_intro_13.png'),
  },
  auth: {
    folder: require('./auth/img_folder.png'),
    piggybank: require('./auth/img_piggybank.png'),
    target: require('./auth/img_target.png'),
    shield: require('./auth/img_shield.png'),
    background_01: require('./auth/img_background_01.png'),
    background_02: require('./auth/img_background_02.png'),
    hand: require('./auth/img_hand.png'),
    auth: require('./auth/img_auth.png'),
    frame: require('./auth/img_frame.png'),
    verify: require('./auth/img_verify.png'),
  },
  avatar: {
    avatar: require('./avatar/img_avatar.png'),
    avatar01: require('./avatar/img_avatar_01.png'),
    avatar02: require('./avatar/img_avatar_02.png'),
    avatar03: require('./avatar/img_avatar_03.png'),
    avatar04: require('./avatar/img_avatar_04.png'),
    avatar05: require('./avatar/img_avatar_05.png'),
    avatar06: require('./avatar/img_avatar_06.png'),
    avatar07: require('./avatar/img_avatar_07.png'),
    avatar08: require('./avatar/img_avatar_08.png'),
    avatar09: require('./avatar/img_avatar_09.png'),
    avatar10: require('./avatar/img_avatar_10.png'),
  },
  rectangle: {
    rectangle_01: require('./social/img_rectangle_01.png'),
    rectangle_02: require('./social/img_rectangle_02.png'),
    rectangle_03: require('./social/img_rectangle_03.png'),
    rectangle_04: require('./social/img_rectangle_04.png'),
    rectangle_05: require('./social/img_rectangle_05.png'),
    rectangle_06: require('./social/img_rectangle_06.png'),
  },
  social: {
    photo01: require('./social/img_photo_01.png'),
    photo02: require('./social/img_photo_02.png'),
    photo03: require('./social/img_photo_03.png'),
    photo04: require('./social/img_photo_04.png'),
    photo05: require('./social/img_photo_05.png'),
    photo06: require('./social/img_photo_06.png'),
    photo07: require('./social/img_photo_07.png'),
    photo08: require('./social/img_photo_08.png'),
    person01: require('./social/img_person_01.png'),
    person02: require('./social/img_person_02.png'),
    person03: require('./social/img_person_03.png'),
    person04: require('./social/img_person_04.png'),
  },
  profile_girl: require('./profile/img_girl.png'),
  e_commerce: {
    nft: require('./e-commerce/img_nft_01.png'),
    commerce01: require('./e-commerce/img_home_01.png'),
    commerce02: require('./e-commerce/img_home_02.png'),
    commerce03: require('./e-commerce/img_home_03.png'),
    commerce04: require('./e-commerce/img_commerce_04.png'),
    commerce05: require('./e-commerce/img_commerce_05.png'),
    product01: require('./e-commerce/img_product_01.png'),
    product02: require('./e-commerce/img_product_02.png'),
    product03: require('./e-commerce/img_product_03.png'),
    product04: require('./e-commerce/img_product_04.png'),
    product05: require('./e-commerce/img_product_05.png'),
    product06: require('./e-commerce/img_product_06.png'),
    review:require('./e-commerce/img_review.png'),
    tracking:require('./e-commerce/img_tracking.png'),
    pizza: require('./e-commerce/img_pizza.png'),
    donut: require('./e-commerce/img_donut.png'),
    buger: require('./e-commerce/img_buger.png'),
  },
};
export default Images;
